// Code generator (§13): modular emitters — one file per concern, never one
// giant bundle. Each emitter is deterministic and dependency-light.
import type { ADL, ReconstructionPlan, ReconstructionTarget } from "../types";

export function generateCode(adl: ADL, target: ReconstructionTarget, sceneKebab: string): ReconstructionPlan {
  switch (target) {
    case "css":
      return cssPlan(adl, sceneKebab);
    case "svg":
      return svgPlan(adl, sceneKebab);
    case "canvas":
      return canvasPlan(adl, sceneKebab);
    case "gsap":
      return gsapPlan(adl, sceneKebab);
    case "framer-motion":
      return framerPlan(adl, sceneKebab);
    case "three":
      return threePlan(adl, sceneKebab);
    case "wapi":
    default:
      return wapiPlan(adl, sceneKebab);
  }
}

function header(adl: ADL, tech: string): string {
  return `/* Generated by Animation Brain from ADL scene "${adl.scene}" (${tech}).\n   Duration: ${adl.duration}ms. Edit the ADL, not this output, to change motion. */\n`;
}

function cssPlan(adl: ADL, slug: string): ReconstructionPlan {
  const rules = adl.events
    .map(
      (e, i) => `.${slug} .el-${i} {\n  animation: ${slug}-e${i} ${e.duration}ms ${e.easing ?? "ease-out"} ${(e.startAt ?? 0).toString()}ms both;\n}`,
    )
    .join("\n");
  const keys = adl.events
    .map((e, i) => `@keyframes ${slug}-e${i} {\n  from { opacity: 0; transform: scale(.6); }\n  to { opacity: 1; transform: scale(1); } /* ${e.action}→${e.target} */\n}`)
    .join("\n\n");
  return {
    target: "css",
    reason: "pure CSS keyframes",
    files: [
      { path: `${slug}/${slug}.css`, language: "css", content: `${header(adl, "css")}${rules}\n\n${keys}\n` },
      { path: `${slug}/Scene.tsx`, language: "tsx", content: `${header(adl, "react")}// Render .${slug} with .el-i children per ADL event.\n` },
    ],
    runtimeNotes: ["No runtime dependency; respects prefers-reduced-motion via media query."],
  };
}

function svgPlan(adl: ADL, slug: string): ReconstructionPlan {
  const shapes = adl.objects.map((o) => `  <!-- ${o.id} (${o.type}) -->`).join("\n");
  return {
    target: "svg",
    reason: "SVG shape/path animation",
    files: [
      { path: `${slug}/${slug}.svg`, language: "svg", content: `${header(adl, "svg")}<svg viewBox="0 0 480 360">\n${shapes}\n</svg>\n` },
      { path: `${slug}/animate.ts`, language: "ts", content: `${header(adl, "wapi")}// Animate SVG nodes per ADL events with element.animate().\n` },
    ],
    runtimeNotes: ["Use pathLength=1 + stroke-dashoffset for draw-on effects."],
  };
}

function canvasPlan(adl: ADL, slug: string): ReconstructionPlan {
  return {
    target: "canvas",
    reason: "Canvas 2D particle/organic motion",
    files: [
      {
        path: `${slug}/scene.ts`,
        language: "ts",
        content: `${header(adl, "canvas")}// rAF loop: interpolate ADL events per frame; see ADL ${adl.scene}.\nexport const DURATION = ${adl.duration};\n`,
      },
      { path: `${slug}/particles.ts`, language: "ts", content: `// Particle pool driven by ADL wind/ambient events.\n` },
      { path: `${slug}/SceneCanvas.tsx`, language: "tsx", content: `// <canvas> host with IntersectionObserver gating + reduced-motion.\n` },
    ],
    runtimeNotes: ["Cap DPR at 2; pause offscreen via IntersectionObserver."],
  };
}

function gsapPlan(adl: ADL, slug: string): ReconstructionPlan {
  const tl = adl.events
    .map((e) => `  tl.to("[data-el='${e.target}']", { duration: ${(e.duration / 1000).toFixed(2)}, ease: "${gsapEase(e.easing)}" }, ${(e.startAt ?? 0) / 1000}); // ${e.action}`)
    .join("\n");
  return {
    target: "gsap",
    reason: "GSAP timeline sequencing",
    files: [
      { path: `${slug}/timeline.ts`, language: "ts", content: `${header(adl, "gsap")}import gsap from "gsap";\nexport function buildTimeline() {\n  const tl = gsap.timeline();\n${tl}\n  return tl;\n}\n` },
      { path: `${slug}/triggers.ts`, language: "ts", content: `// ScrollTrigger / IntersectionObserver wiring per ADL triggers.\n` },
      { path: `${slug}/Scene.tsx`, language: "tsx", content: `// React host with data-el ids.\n` },
    ],
    runtimeNotes: ["Requires gsap ^3.12."],
  };
}

function framerPlan(adl: ADL, slug: string): ReconstructionPlan {
  return {
    target: "framer-motion",
    reason: "Framer Motion variants",
    files: [
      { path: `${slug}/variants.ts`, language: "ts", content: `${header(adl, "framer-motion")}// Variants per ADL event (mount/presence).\n` },
      { path: `${slug}/Scene.tsx`, language: "tsx", content: `// motion.* components consuming variants.\n` },
    ],
    runtimeNotes: ["Requires framer-motion (already a project dependency)."],
  };
}

function wapiPlan(adl: ADL, slug: string): ReconstructionPlan {
  return {
    target: "wapi",
    reason: "Web Animations API keyframes",
    files: [
      { path: `${slug}/keyframes.ts`, language: "ts", content: `${header(adl, "wapi")}// Keyframe arrays per ADL event for element.animate().\n` },
      { path: `${slug}/player.ts`, language: "ts", content: `// Orchestrate players per ADL triggers.\n` },
    ],
    runtimeNotes: ["Zero dependencies; runs natively in browsers."],
  };
}

function threePlan(adl: ADL, slug: string): ReconstructionPlan {
  return {
    target: "three",
    reason: "Three.js camera/3D motion",
    files: [
      { path: `${slug}/scene.ts`, language: "ts", content: `${header(adl, "three")}// three.js scene graph mirroring ADL objects.\n` },
      { path: `${slug}/camera.ts`, language: "ts", content: `// Camera rig (push-in / follow) per ADL camera events.\n` },
    ],
    runtimeNotes: ["Requires three; only chosen when 2D targets cannot express the motion."],
  };
}

function gsapEase(easing?: string): string {
  const e = (easing ?? "").toLowerCase();
  if (e.includes("linear")) return "none";
  if (e.includes("easeinout")) return "power2.inOut";
  if (e.includes("easein")) return "power2.in";
  if (e.includes("spring") || e.includes("elastic")) return "elastic.out(1,0.6)";
  if (e.includes("bounce")) return "bounce.out";
  return "power2.out";
}
